import{a as f,i as y}from"./assets/vendor-2dcf4ad5.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="https://api.thecatapi.com/v1/breeds",b="live_EBVwqoCwGqVHhvUbbkYhpgTBviI9U780AwppN2kkrGGngpAKibNs1Xq1TqOHZ8iA";f.defaults.headers.common["x-api-key"]=b;function w(){return f.get(S).then(n=>n.data)}function v(n){const i="https://api.thecatapi.com/v1/images/search";return f.get(i,{params:{breed_ids:n}}).then(s=>s.data)}document.addEventListener("DOMContentLoaded",function(){const n={breedSelect:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader")},i=new SlimSelect({select:n.breedSelect,placeholder:"Select a breed",showSearch:!0,searchText:"No matches found",searchPlaceholder:"Search...",searchHighlight:!0,searchFocus:!0,allowDeselect:!1,onChange:l});function s(e){n.catInfo.innerHTML=c(e)}function l(){const e=i.selected();n.catInfo.innerHTML="",e&&d(),v(e).then(o=>{o&&o.length>0?s(o):u("Oops! Something went wrong! Try reloading the page!")}).catch(o=>m(o)).finally(()=>{e&&(h(),p())})}function t(){return d(),w().then(e=>{e&&e.length>0?r(e):u("No cat breeds received or empty array!")}).catch(e=>m(e)).finally(()=>{h(),p()})}function r(e){i.setData(e.map(o=>({text:o.name,value:o.id})))}function c(e){return e.map(({url:o,breeds:g})=>{const[a]=g;return`
          <img src="${o}" alt="${a.name}" width="300">
          <div>
            <h3>${a.name}</h3>
            <p><strong>Description:</strong> ${a.description}</p>
            <p><strong>Temperament:</strong> ${a.temperament}</p>
          </div>
        `}).join("")}function d(){n.loader.style.display="block"}function h(){n.loader.style.display="none"}function p(){i.slim.container.style.display="block"}function m(e){console.error("Error:",e),u("Oops! Something went wrong! Try reloading the page!")}function u(e){y.error({title:"Error",message:e,position:"topRight"})}d(),t()});
//# sourceMappingURL=commonHelpers.js.map
